spring:
  datasource:
    url: **
    #    url: **
    username: **
    password: **
  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB




