spring:
  datasource:
    url: jdbc:mysql://114.132.251.197:3306/onlineclass
    #    url: jdbc:mysql://47.92.160.213:3306/onlineclass
    username: OnlineClass
    password: TGxpGTetSxmnKepA
  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB




